const arreglo2 = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F']; //AQUI HE CREADO EL ARREGLO QUE CONTIENE TODOS LOS VALORES POSIBLES DENTRO DE UNA PALETA DE COLORES CSS//
function cambiartono() { //AQUI SE CREA UNA FUNCION QUE GENERA UN COLOR ALEATORIO 
let tono = '#'; //AQUI ESTABLECEMOS LA VARIBLES LLAMADA TONO CON EL CARACTER # QUE ES EL PREFIJO PARA LOS COLORES EN CSS
for (let i = 0; i < 6; i++) { //AQUI HE CREADO UN BUCLE FOR QUE DEVUELVE 6 VALORES AL AZAR DENTRO DEL ARREGLO CREADO 
tono += arreglo2[Math.floor(Math.random() * arreglo2.length)];
}
return tono;//DEVUELVE EL RESULTADO DE LA VARIABLE TONO QUE SERA UN CODIGO DE UN COLOR DE LA PALETA CSS
}
function paleta() { //AQUI HE CREADO UNA FUNCION LLAMADA PALETA QUE LLAMA A LA FUNCION CAMBIARTONO PARA OBTENER EL VALOR DE LOS 6 DIGITOS QUE DEVUELVE DEL ARREGLO AL AZAR Y ASIGNARLO A AL ELEMENTO PRUEBA2
const prueba2 = cambiartono();
document.body.style.backgroundColor = prueba2; //LUEGO PROCEDE A CAMBIAR EL COLOR DE FONDO DE LA PAGINA AL DEL ELEMENTO PRUEBA2  
document.getElementById('palabras').textContent = prueba2; //AQUI ACTUALIZA EL CONTENIDO DEL ELEMENTO PALABRAS PARA MOSTRAR LOS 6 DIGITOS EN TEXTOS GENERADOS AL AZAR
}
document.getElementById('cambiador2').addEventListener('click', paleta); //POR ULTIMO ASIGNAMOS UN EVENT LISTENER AL ELEMENTO CAMBIADOR2 DE TIPO CLICK PARA QUE CUANDO SE DE CLICK LLAME A LA FUNCION PALETA
